language: java
jdk: 
  - openjdk11
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE interstellar_test;' -U postgres
  - psql -c "CREATE USER interstellar_test WITH ENCRYPTED PASSWORD 'interstellar_test';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE interstellar_test TO interstellar_test;' -U postgres