language: java
jdk: 
  - openjdk11
services:
  - postgresql
before_script:
  - psql -c "CREATE USER interstellar_test WITH PASSWORD interstellar_test;" -U postgres
  - psql -c "CREATE DATABASE interstellar_test WITH OWNER = interstellar_test;" -U postgres